### ISSUE TITLE
Found some issues with my proprietary analyzer tool.

### ISSUE THREAD

**Issue by regmicmahesh** [ASACHIT/Hotel-booking-ui-flutter#1]
info • Name non-constant identifiers using lowerCamelCase • lib/pages/dashboard.dart:17:9 • non_constant_identifier_names
   info • Name types using UpperCamelCase • lib/pages/widgets/recommendation.dart:3:7 • camel_case_types
   info • Name types using UpperCamelCase • lib/pages/widgets/recommendation.dart:21:7 • camel_case_types

**Comment by ASACHIT** [comment]
addressed those mentioned warnings !

**Comment by regmicmahesh** [comment]
thanks. looking forward for a **swag**.
